# AppSec-Sentinel Clippy Configuration for Rust Code Quality
# Clippy is the official Rust linter with 600+ lint checks

# Warn on all clippy lint groups
[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"

# Allow some pedantic lints that are too noisy or opinionated
too_many_arguments = "allow"
must_use_candidate = "allow"
module_name_repetitions = "allow"

# Enable useful lints that aren't in default groups
missing_docs_in_private_items = "warn"
unwrap_used = "warn"
expect_used = "warn"
